local default_icons = {
  kind = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
  type = {
    Array = "",
    Container = "⦿",
    Function = "",
    Number = "",
    String = "",
    Boolean = "蘒",
    Object = "",
  },
  documents = {
    File = "",
    Files = "",
    Folder = "",
    OpenFolder = "",
  },
  git = {
    Add = "",
    Mod = "",
    Remove = "",
    Ignore = "",
    Rename = "",
    Diff = "",
    Repo = "",
    Octoface = "",
  },
  ui = {
    ArrowClosed = "",
    ArrowOpen = "",
    Lock = "",
    Circle = " ",
    BigCircle = "",
    BigUnfilledCircle = " ",
    Close = "",
    NewFile = " ",
    Search = "",
    Lightbulb = "",
    Project = " ",
    Dashboard = "",
    History = " ",
    Comment = " ",
    Bug = " ",
    Code = "",
    Telescope = " ",
    Gear = " ",
    Package = "",
    List = " ",
    SignIn = " ",
    SignOut = "",
    Check = "",
    Fire = "",
    Note = " ",
    BookMark = "",
    Pencil = " ",
    -- ChevronRight = "",
    ChevronRight = ">",
    Table = "",
    Calendar = " ",
    CloudDownload = "",
    Plus = "+",
    RunningMan = "🏃",
    Yoga = "🧘",
    Xmark = "✗",
    Diamond = "<>",
  },
  diagnostics = {
    Error = "",
    Warning = "",
    Information = "",
    Question = "",
    Hint = "",
  },
  misc = {
    Robot = "ﮧ",
    Squirrel = "",
    Tag = "",
    Watch = "",
    Smiley = "ﲃ",
    Package = "",
    CircuitBoard = "",
  },
}

local status_ok, icons = pcall(require, "nvim-web-devicons")
if not status_ok then
  return default_icons
end

icons.set_icon {
  deb = { icon = "", name = "Deb" },
  lock = { icon = "", name = "Lock" },
  mp3 = { icon = "", name = "Mp3" },
  mp4 = { icon = "", name = "Mp4" },
  out = { icon = "", name = "Out" },
  ["robots.txt"] = { icon = "ﮧ", name = "Robots" },
  ttf = { icon = "", name = "TrueTypeFont" },
  rpm = { icon = "", name = "Rpm" },
  woff = { icon = "", name = "WebOpenFontFormat" },
  woff2 = { icon = "", name = "WebOpenFontFormat2" },
  xz = { icon = "", name = "Xz" },
  zip = { icon = "", name = "Zip" },
}

return default_icons
