return {
  icon = {
    comment = {
      Note = "󱞁",
      Todo = "",
      Warn = "",
      Error = "ﰡ",
      Hack = "󱜯",
      Fix = "ﮉ",
    },
    kind = {
      Default = "",
      String = "",
      Array = "",
      Boolean = "",
      Class = "",
      Color = "",
      Container = "⦿",
      Constant = "",
      Constructor = "",
      Copilot = "",
      Enum = "",
      EnumMember = "",
      Event = "",
      Field = "",
      File = "",
      Folder = "",
      Function = "",
      Interface = "",
      Key = "",
      Keyword = "",
      Method = "",
      Module = "",
      Namespace = "",
      Null = "",
      Number = "",
      Object = "",
      Operator = "",
      Package = "",
      Property = "",
      Reference = "",
      Snippet = "",
      Struct = "",
      Text = "",
      TypeParameter = "",
      Unit = "",
      Value = "",
      Variable = "",
      Macro = "", -- Macro
    },
    documents = {
      File = "",
      Files = "",
      Folder = "",
      OpenFolder = "",
    },
    gitsigns = {
      add = "┃",
      change = "┋",
      delete = "",
      topdelhfe = "",
      changedelete = "┃",
      untracked = "┃",
    },
    git = {
      Git = "",
      Add = "",
      Mod = "",
      Remove = "",
      Ignore = "",
      Rename = "",
      Diff = "",
      Repo = "",
      Octoface = "",

      untracked = "",
      ignored = "",
      unstaged = "U",
      staged = "",
      conflict = "",
      deleted = "",
    },
    neo_tree = {
      filesystem = "󰉓",
      buffers = "󰈙",
      git_status = "",
      diagnostics = "󰒡",

      folder_closed = "",
      folder_open = "",
      folder_empty = "",
      folder_empty_open = "",
      default = " ",

      symbol = "",
    },
    ui = {
      ArrowClosed = "",
      ArrowOpen = "",
      Lock = "",
      LeftTruncMarker = "",
      RightTruncMarker = "",
      Circle = " ",
      BigCircle = "",
      BigUnfilledCircle = " ",
      BufferClose = "󰅚",
      Close = "󰅙",
      NewFile = " ",
      Search = "󰥌",
      Lightbulb = "",
      Project = " ",
      Dashboard = "",
      History = " ",
      Comment = " ",
      Bug = " ",
      Code = "",
      Telescope = " ",
      Gear = " ",
      Package = "",
      List = " ",
      SignIn = " ",
      SignOut = "",
      Check = "",
      Fire = "",
      Note = " ",
      BookMark = "",
      Pencil = " ",
      ChevronRight = ">",
      Table = "",
      Calendar = " ",
      CloudDownload = "",
      Plus = "+",
      RunningMan = "🏃",
      Yoga = "🧘",
      Xmark = "✗",
      Diamond = "<>",
    },
    diagnostic = {
      Error = "",
      Warning = "",
      Information = "",
      Question = "",
      Hint = "",
    },
    misc = {
      Robot = "ﮧ",
      Squirrel = "",
      Tag = "",
      Watch = "",
      Smiley = "ﲃ",
      Package = "",
      CircuitBoard = "",
      Lsp = "",
    },
  },
}
