local function load_options()
    local option_local = {
        termguicolors = true,
        mouse = "a",
        errorbells = true,
        visualbell = true,
        hidden = true,
        fileformats = "unix,mac,dos",
        magic = true,
        virtualedit = "block",
        encoding = "utf-8",
        viewoptions = "folds,cursor,curdir,slash,unix",
        sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal",
        clipboard = "unnamedplus",
        wildignorecase = true,
        wildignore = ".git,.hg,.svn,*.pyc,*.o,*.out,*.jpg,*.jpeg,*.png,*.gif,*.zip,**/tmp/**,*.DS_Store,**/node_modules/**,**/bower_modules/**",
        backup = false,
        writebackup = false,
        swapfile = false,
        history = 2000,
        shada = "!,'300,<100,@50,s1000,:0,h",
        backupskip = "/tmp/*,$TMPDIR/*,$TMP/*,$TEMP/*,*/shm/*,/private/var/*,.vault.vim",
        smarttab = true,
        shiftround = true,
        timeout = true,
        ttimeout = true,
        timeoutlen = 500,
        ttimeoutlen = 0,
        updatetime = 100,
        redrawtime = 1500,
        ignorecase = true,
        smartcase = true,
        infercase = true,
        incsearch = true,
        wrapscan = true,
        complete = ".,w,b,k",
        inccommand = "nosplit",
        grepformat = "%f:%l:%c:%m",
        grepprg = "rg --hidden --vimgrep --smart-case --",
        breakat = [[\ \	;:,!?]],
        startofline = false,
        whichwrap = "h,l,<,>,[,],~",
        splitbelow = true,
        splitright = true,
        switchbuf = "useopen",
        backspace = "indent,eol,start",
        diffopt = "filler,iwhite,internal,algorithm:patience",
        completeopt = "menuone,noselect",
        jumpoptions = "stack",
        showmode = false,
        shortmess = "aoOTIcF",
        scrolloff = 5,
        sidescrolloff = 5,
        foldlevelstart = 99,
        ruler = true,
        list = true,
        showtabline = 2,
        winwidth = 30,
        winminwidth = 10,
        pumheight = 15,
        helpheight = 12,
        previewheight = 12,
        showcmd = false,
        cmdheight = 1,
        cmdwinheight = 7,
        equalalways = false,
        laststatus = 2,
        display = "lastline",
        showbreak = "↳  ",
        listchars = "tab:»·,nbsp:+,trail:·,extends:→,precedes:←",
        pumblend = 10,
        winblend = 10,
        autoread = true,
        autowrite = true,
        colorcolumn = "81,101"
    }
    for name, value in pairs(option_local) do vim.o[name] = value end

    local bw_local = {
        undofile = true,
        synmaxcol = 2500,
        formatoptions = "1jcroql",
        textwidth = 80,
        expandtab = true,
        autoindent = true,
        tabstop = 4,
        shiftwidth = 4,
        softtabstop = -1,
        breakindentopt = "shift:2,min:20",
        wrap = false,
        linebreak = true,
        number = true,
        relativenumber = true,
        foldenable = true,
        signcolumn = "yes",
        conceallevel = 0,
        concealcursor = "niv"
    }
    for k, v in pairs(bw_local) do
        if v == true then
            vim.cmd("set " .. k)
        elseif v == false then
            vim.cmd("set no" .. k)
        else
            vim.cmd("set " .. k .. "=" .. v)
        end
    end

    local global_local = {
        clipboard = {
            name = "macOS-clipboard",
            copy = {["+"] = "pbcopy", ["*"] = "pbcopy"},
            paste = {["+"] = "pbpaste", ["*"] = "pbpaste"},
            cache_enabled = 0
        },
        python_host_prog = "/usr/bin/python",
        python3_host_prog = "/usr/local/bin/python3",
        did_load_filetypes = 1,
        did_load_fzf = 1,
        did_load_gtags = 1,
        did_load_gzip = 1,
        did_load_tar = 1,
        did_load_tarPlugin = 1,
        did_load_zip = 1,
        did_load_zipPlugin = 1,
        did_load_getscript = 1,
        did_load_getscriptPlugin = 1,
        did_load_vimball = 1,
        did_load_vimballPlugin = 1,
        did_load_matchit = 1,
        did_load_matchparen = 1,
        did_load_2html_plugin = 1,
        did_load_logiPat = 1,
        did_load_rrhelper = 1,
        did_load_netrw = 1,
        did_load_netrwPlugin = 1,
        did_load_netrwSettings = 1,
        did_load_netrwFileHandlers = 1,
        loaded_python_provider = 0,
        loaded_perl_provider = 0,
        loaded_ruby_provider = 0,
    }
    for name, value in pairs(global_local) do vim.g[name] = value end

end

load_options()
